@startuml "Ros2_Opcua_server_class.wsd"


package "OPCUA Server" {
    class "OpcuaServer" as opcua_server {
    
    }
}

package "OPCUA Confgiuration" {
    class "OpcuaServerConfig" as opcua_server_config {
    
    }
}

package "OPCUA ROS2 Messages" {
    class "JoitnStateToOpcua" as joint_state_to_opcua {

    
    }
    class "CartesianToOpcua" as cartesian_to_opcua {
    
    }
    class "OpcuaToCartesian" as opcua_to_cartesian {
    
    }
}
package "OPCUA Ros2 Control" {
    class "OpcuaControl" as opcua_control {
    
    }
}

package "OPCUA ROS2 Utils" {
    class "OpcuaUtils" as opcua_utils {
    
    }
}



@enduml
