@startuml "robot_urdf"

!include ./Templates/urdf/links.wsd
!include ./Templates/urdf/joints.wsd
!include ./Templates/urdf/links_to_joints.wsd
!include ./Templates/urdf/gazebo_control_plugin.wsd
!include ./Templates/urdf/gazebo_material.wsd
!include ./Templates/urdf/ros2_control_hardware.wsd
!include ./Templates/urdf/ros2_control_joints.wsd


left to right direction
'skinparam linetype ortho


skinparam rectangle<<urdf>> {
    backgroundColor LightGray
}

skinparam rectangle<<robot>> {
    backgroundColor Azure
    Shadowing true

}

skinparam rectangle<<robot_part>> {
    backgroundColor FloralWhite
        Shadowing true
}

skinparam rectangle<<gazebo>> {
    backgroundColor BurlyWood
    Shadowing true
}

skinparam rectangle<<ros2_control>> {
    backgroundColor Lavender
    Shadowing true
}

rectangle Kr3r540_urdf_xacro <<urdf>> {

rectangle Kr3r540 <<robot>> {
        rectangle Links <<robot_part>> {

        $link("Base_Link", "0 0 0", "11.37", "0.537", "0.002", "0.014", "0.804", "0.0", "0.745")
        $link("Link_1", "0 0 0.345", "7", "0.361", "-0.001", "-0.0014", "0.255", "-0.007", "0.29")
        $link("Link_2", "0.020 0 0", "6.9", "0.249", "-0.007", "-0.021", "0.573", "-0.001", "0.708")
        $link("Link_3", "0 0 0", "3", "0.005464170195346057", "0.00002317865761359266", "-0.0008376172568479034", "0.009668497673794239", "-0.0000053812765981131285", "0.009530838326239676")
        $link("Link_4", "0 0 0", "2", "0.04", "-0.004", "0.0", "0.045", "-0.001", "0.063")
        $link("Link_5", "0 0 0", "1", "0.0009523921025026232", "-0.000014859377039896955", "-0.00000026599547296907754", "0.001277581091791774", "0.00000029443366764204974", "0.0014178861490860182")
        $link("Link_6", "0 0 0", "0.03", "0.0000097510332695528", "-0.00000005535554975934552", "0.00000010491860620923319", "0.000005458075446678377", "-0.00000030083248575603903", "0.00000545822894382603")
        $link("greifer_base", "0 0 0", "0.19", "0.008552", "-0.000097", "0", "0.002908", "0.000004", "0.009732")
        $link("greifer_finger_1", "0 0 0", "0.01", "0.001876", "-0.001122", "0.000392", "0.004166", "0.000374", "0.005261")
        $link("greifer_finger_2", "0 0 0", "0.01", "0.00103", "0.000654", "0.000219", "0.002527", "-0.000204", "0.00313")

        $link_to_joint(Link_1,Base_Link,joint_1)
        $link_to_joint(Link_2,Link_1,joint_2)
        $link_to_joint(Link_3,Link_2,joint_3)
        $link_to_joint(Link_4,Link_3,joint_4)
        $link_to_joint(Link_5,Link_4,joint_5)
        $link_to_joint(Link_6,Link_5,joint_6)
        $link_to_joint(greifer_base,Link_6,flange)
        $link_to_joint(greifer_finger_1,greifer_base,flange_finger_1)
        $link_to_joint(greifer_finger_2,greifer_base,flange_finger_2)

        }

        rectangle Gazebo_Ignition <<gazebo>> {
            $gazebo_control_plugin("libign_ros2_control-system.so", "IgnitionROS2ControlPlugin", "kr3r540_sim_controllers.yaml", "kr3r540_sim", "/tf:=/kr3r540_sim/tf, /tf_static:=/kr3r540_sim/tf_static")
            
            $gazebo_material("base_link", "Red")
            $gazebo_material("link_1", "White")
            $gazebo_material("link_2", "White")
            $gazebo_material("link_3", "White")
            $gazebo_material("link_4", "White")
            $gazebo_material("link_5", "White")
            $gazebo_material("link_6", "White")
            $gazebo_material("greifer", "DarkGrey")
        }
        rectangle Joints <<robot_part>>{

            rectangle Arm <<robot_part>> {
                $joint("joint_1", "revolute", "base_link", "link_1", "0 0 0.345", "0 0 0", "0 0 -1", "-2.967", "2.967", "1000", "9.266")
                $joint("joint_2", "revolute", "link_1", "link_2", "0.020 0 0", "0 0 0", "0 1 0", "-2.967", "0.872665", "1000", "9.233")
                $joint("joint_3", "revolute", "link_2", "link_3", "0.260 0 0", "0 0 0", "0 1 0", "-1.919", "2.705", "1000", "9.389")
                $joint("joint_4", "revolute", "link_3", "link_4", "0 0 0.020", "0 0 0", "-1 0 0", "-3.054", "3.054", "1000", "10.472")
                $joint("joint_5", "revolute", "link_4", "link_5", "0.260 0 0", "0 0 0", "0 1 0", "-2.094", "2.094", "1000", "10.472")
                $joint("joint_6", "revolute", "link_5", "link_6", "0.075 0 0", "0 0 0", "-1 0 0", "-6.108", "6.108", "1000", "13.962")
            }

            rectangle Connector <<robot_part>> {
                $joint("flange", "fixed", "link_6", "greifer_base", "0.013 0 0.02", "1.57 -3.1416 -1.57", "N/A", "N/A", "N/A", "N/A", "N/A")
            }

            rectangle Gripper <<robot_part>> {
            $joint("flange_finger_1", "prismatic", "greifer_base", "greifer_finger_1", "0 0 0", "0 0 0", "1 0 0", "0", "0.006", "100", "0.1")
            $joint("flange_finger_2", "prismatic", "greifer_base", "greifer_finger_2", "0 0 0", "0 0 0", "-1 0 0", "0", "0.006", "100", "0.1")
            }


        }
        rectangle Ros2_control <<ros2_control>> {
            $ros2_hardware("IgnitionSystem", "None", "true")
            $ros2_hardware("Kr3r540Interface","ip , port", "false")
            $ros2_control_joints("joint1", "position", "position")
            $ros2_control_joints("joint2", "position", "position")
            $ros2_control_joints("joint3", "position", "position")
            $ros2_control_joints("joint4", "position", "position")
            $ros2_control_joints("joint5", "position", "position")
            $ros2_control_joints("joint6", "position", "position")
            $ros2_control_joints("flange_finger1", "position", "position")
            $ros2_control_joints("flange_finger2", "position", "position")
            
        }
    }
}


@enduml