@startuml "KukaDigitalTwin"


left to right direction
skinparam packageStyle rect
actor User as AC
rectangle "KukaVerse" {

    usecase "UC1\nLoginMode" as UC1 
    usecase "UC2\nHomeMode" as UC2
    usecase "UC3\nDevicesMode" as UC3
    usecase "UC4\nAddDeviceMode" as UC4
    usecase "UC5\nConnectionMode" as UC5
    usecase "UC6\nSimulationMode" as UC6
    usecase "UC7\nControlPanelMode" as UC7
    usecase "UC8\nLogoutMode" as UC8
}
AC -- UC1
AC -- UC2
AC -- UC3
AC -- UC4
AC -- UC5
AC -- UC6
AC -- UC7
AC -- UC8
@enduml