kr3r540_sim:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      use_sim_time: true


      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  arm_controller:
    ros__parameters:
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
      
      command_interfaces:
        - position
      
      state_interfaces:
        - position
        - velocity
      
      allow_integration_in_goal_trajectories: true
      open_loop_control: true
      