controller_manager:
  ros__parameters:
    update_rate: 50.0
    use_sim_time: true

kr3r540_sim_joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

kr3r540_sim_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 200.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 1.0
      joint_1:
        trajectory: 0.1
      joint_2:
        trajectory: 0.1
      joint_3:
        trajectory: 0.1
      joint_4:
        trajectory: 0.1
      joint_5:
        trajectory: 0.1
      joint_6:
        trajectory: 0.1
